name: "Bitcoin Bot Smart2"
version: "5.2"
changelog: "./btc_bot/CHANGELOG.md"
slug: "btc_bot"
description: "A Telegram bot that sends daily Bitcoin updates"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  TOKEN: "your-token-here"
  CHAT_ID: "your-chat-id-here"
  GSHEET_URL: "link-to-your-google-sheet"
  JSON_KEYS: "your-google-json-content"
  OPENAI_API_KEY: "your-openai-api-key"
  BINANCE_API_KEY: "your-binance-api-key"
  BINANCE_API_SECRET: "your-binance-api-secret"
schema:
  TOKEN: password
  CHAT_ID: str
  GSHEET_URL: password
  JSON_KEYS: password
  OPENAI_API_KEY: password
  BINANCE_API_KEY: password
  BINANCE_API_SECRET: password
